# Generated by Django 5.2.7 on 2025-11-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='buzzline.profile'),
        ),
    ]
