# Generated by Django 5.2.7 on 2025-11-25 20:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buzzline', '0004_beeps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beeps',
            new_name='Beep',
        ),
    ]
